"url"= "https://idcs-5d9e793985524e1c80b5d96f9a03acb7.identity.oraclecloud.com/admin/v1/IdentityPropagationTrusts"
"issuer"= "https://token.actions.githubusercontent.com"
"name"= "gitHubOIDC"
"oauthClients" = "7cd697ab037044159c0c10d74769c0bb"
"publicKeyEndpoint" = "https://bitbucket.org/gordontrevorrow/diary/raw/21f0b916abfdaae694abd8dc7fe0ee1c37032320/jwks.json"
"subjectClaimName"= "actor_id"
"subjectType" = "User"
"type"= "JWT"
"subjectMappingAttribute" = "userName"
"allowImpersonation" = true
"id" = "0072a176c26b4992a4351ebe0af17caa"